build.gradle, src/main/java/stg/onyou/controller/UserController.java, src/main/java/stg/onyou/model/network/Header.java, src/main/resources/application.properties
API 문서 자동화를 위한 Swagger 설정 
- springfox dependency 추가
- spring2.6에서 발생하는 버그를 위한 spring path matching 설정 추가 (app.properties)
=> Swagger UI 설정

src/main/java/stg/onyou/controller/ClubController.java, src/main/java/stg/onyou/controller/UserController.java, src/main/java/stg/onyou/exception/ExceptionResponse.java, src/main/java/stg/onyou/exception/GlobalExceptionHandler.java, src/main/java/stg/onyou/exception/UserNotFoundException.java
예외처리 커스터마이징 할 수 있도록 GloablExceptionHandler와 ExceptionResponse 추가 했습니다.
=> 예외처리 클래스 추가

src/main/java/stg/onyou/exception/CustomException.java, src/main/java/stg/onyou/exception/ErrorCode.java, src/main/java/stg/onyou/exception/ExceptionResponse.java, src/main/java/stg/onyou/exception/GlobalExceptionHandler.java, src/main/java/stg/onyou/exception/UserNotFoundException.java
=> Custom Exception 구현 ( 예외처리 방식 수정 )

src/main/java/stg/onyou/controller/FeedController.java, src/main/java/stg/onyou/model/entity/Feed.java, src/main/java/stg/onyou/repository/FeedRepository.java, src/main/java/stg/onyou/repository/FeedRepositoryImpl.java, src/main/java/stg/onyou/service/FeedService.java
feed 관련 controller, service, repository, model 코드
=> spring feed 관련 코드 개발

src/main/java/stg/onyou/controller/ClubController.java, src/main/java/stg/onyou/controller/FeedController.java, src/main/java/stg/onyou/controller/UserController.java, src/main/java/stg/onyou/model/entity/Category.java, src/main/java/stg/onyou/model/entity/Club.java, src/main/java/stg/onyou/model/entity/Feed.java, src/main/java/stg/onyou/model/entity/Organization.java, src/main/java/stg/onyou/model/entity/UserClub.java, src/main/java/stg/onyou/model/network/response/ClubApiResponse.java, src/main/java/stg/onyou/model/network/response/UserApiResponse.java, src/main/java/stg/onyou/repository/ClubRepository.java, src/main/java/stg/onyou/service/ClubApiService.java, src/main/java/stg/onyou/service/FeedService.java, src/main/java/stg/onyou/service/UserApiService.java, src/main/resources/application.properties
clubApi 구현했습니다.
- Club Entity와  User, Category, UserClub Entity 사이에 JPA 관계 설정
- User Entity와 UserClub Entity 사이에 JPA 관계 설정
- ClubApiService 구현
=> clubApi 구현

src/main/java/stg/onyou/controller/ClubController.java, src/main/java/stg/onyou/exception/ErrorCode.java, src/main/java/stg/onyou/exception/ExceptionResponse.java, src/main/java/stg/onyou/model/entity/Category.java, src/main/java/stg/onyou/model/entity/Club.java, src/main/java/stg/onyou/model/entity/Organization.java, src/main/java/stg/onyou/model/network/Header.java, src/main/java/stg/onyou/service/ClubApiService.java, src/main/java/stg/onyou/service/UserApiService.java
1. 모든 club에 대한 데이터를 GET 하는 API 추가하였습니다.
DTO 폼에 맵핑하려다 보니 코드가 다소 길어졌는데 
추후에 공통된 부분들은 별도 함수로 빼는 걸로 리팩토링 해보겠습니다. 
2. 기존에 Header클래스의 Error 메소드에서 일괄 에러 처리하던 것을 
지난 번에 구현한 CustomException을 사용하여 없는 user, club에 대한 요청에 대해서 handling할 수 있도록 수정했습니다.
=> selectAllClubs 추가, CustomException 적용

build.gradle, src/main/java/stg/onyou/controller/UserController.java, src/main/java/stg/onyou/model/entity/User.java, src/main/java/stg/onyou/repository/UserRepository.java, src/main/java/stg/onyou/service/ClubApiService.java, src/main/java/stg/onyou/service/UserApiService.java
1) 사용자 정보 조회 기능 추가
2) 종원오빠가 sex의 타입을 enum으로 바꾸면 좋을 것 같다고는데 아직 반영은 안했어요(회의하려구)
=> 20220309_kakao Login commit

src/main/java/stg/onyou/controller/ClubController.java, src/main/java/stg/onyou/model/entity/Club.java, src/main/java/stg/onyou/model/entity/User.java, src/main/java/stg/onyou/model/network/Header.java, src/main/java/stg/onyou/model/network/request/ClubCreateRequest.java, src/main/java/stg/onyou/service/ClubApiService.java, src/main/java/stg/onyou/service/UserApiService.java
=> clubAPI 리팩토링

src/main/java/stg/onyou/controller/FeedController.java, src/main/java/stg/onyou/model/entity/FeedHashtag.java, src/main/java/stg/onyou/model/entity/FeedImage.java, src/main/java/stg/onyou/model/entity/Hashtag.java, src/main/java/stg/onyou/repository/FeedRepository.java, src/main/java/stg/onyou/service/FeedService.java
feed CRUD service 구현
TODO 
1. Feed-Hashtag, Feed-Club, Feed-Image Join
2. 
2.1 해시태그 검색
2.2 그룹 내 feed 검색
2.3 Like, Comment entity 추가
TO DISCUSS
1. feed 신고 - reportYn?
=> 20220309 find feed api

src/main/java/stg/onyou/controller/UserController.java
=> 카카오 로그인 수정: front로부터 token받도록

.gitignore, build.gradle, logs/access_log.2022-04-05.log, src/main/java/stg/onyou/config/SecurityConfig.java, src/main/java/stg/onyou/service/UserApiService.java, src/main/resources/application.properties
=> Spring security 설정

build.gradle, src/main/java/stg/onyou/config/BeanConfiguration.java, src/main/java/stg/onyou/config/SecurityConfig.java, src/main/java/stg/onyou/controller/CategoryController.java, src/main/java/stg/onyou/exception/ErrorCode.java, src/main/java/stg/onyou/model/network/response/CategoryResponse.java, src/main/java/stg/onyou/service/CategoryApiService.java
1. ModelMapper 추가 : Entity -> DTO 변환을 쉽게 해줌 ( 참고 : https://thalals.tistory.com/230 )
2. selectAllCategories API 추가
=> 20220410 pr

build.gradle, src/main/java/stg/onyou/config/CorsConfig.java, src/main/java/stg/onyou/config/SecurityConfig.java, src/main/java/stg/onyou/config/auth/LoadUserService.java, src/main/java/stg/onyou/config/auth/PrincipalDetails.java, src/main/java/stg/onyou/config/auth/PrincipalDetailsService.java, src/main/java/stg/onyou/config/jwt/AccessTokenAuthenticationProvider.java, src/main/java/stg/onyou/config/jwt/AccessTokenKakao.java, src/main/java/stg/onyou/config/jwt/JwtAuthenticationFilter.java, src/main/java/stg/onyou/config/jwt/JwtAuthorizationFilter.java, src/main/java/stg/onyou/config/jwt/JwtProperties.java, src/main/java/stg/onyou/model/Role.java, src/main/java/stg/onyou/model/entity/User.java, src/main/java/stg/onyou/repository/UserRepository.java, src/main/resources/application.properties
카카오 로그인을 위한 Spring Security 설정 ( 테스트 )
=> 20220414 security

build.gradle, src/main/java/stg/onyou/controller/FeedController.java, src/main/java/stg/onyou/model/AccessModifier.java, src/main/java/stg/onyou/model/RecruitStatus.java, src/main/java/stg/onyou/model/entity/Club.java, src/main/java/stg/onyou/model/entity/Comment.java, src/main/java/stg/onyou/model/entity/Feed.java, src/main/java/stg/onyou/model/entity/FeedHashtag.java, src/main/java/stg/onyou/model/entity/FeedImage.java, src/main/java/stg/onyou/model/entity/FeedSearch.java, src/main/java/stg/onyou/model/entity/Good.java, src/main/java/stg/onyou/model/network/request/FeedCreateRequest.java, src/main/java/stg/onyou/model/network/request/FeedUpdateRequest.java, src/main/java/stg/onyou/model/network/response/ClubApiResponse.java, src/main/java/stg/onyou/model/network/response/FeedResponse.java, src/main/java/stg/onyou/repository/FeedRepository.java, src/main/java/stg/onyou/service/ClubApiService.java, src/main/java/stg/onyou/service/FeedService.java
Feed CRUD API 완료
Todo
Feed content 내 hashtag 발라내는 로직짜기
CreateFeedRequest로 받은 사진 파일을 s3에 올리기
Feed Search 기능은 동적쿼리 QueryDSL 공부한 이후에.
좋아요와 댓글은 그 이후로.
=> Feed CRUD API

src/main/java/stg/onyou/config/SecurityConfig.java, src/main/java/stg/onyou/config/auth/LoadUserService.java, src/main/java/stg/onyou/config/jwt/AccessTokenAuthenticationProvider.java, src/main/java/stg/onyou/config/jwt/JwtAuthenticationFilter.java, src/main/java/stg/onyou/config/jwt/LoginFailHandler.java, src/main/java/stg/onyou/config/jwt/LoginSuccessHandler.java
Security 설정 수정
- LoginFailHandler, LoginSuccessHandler 추가
- Security Config 수정 
- JwtAuthenticationFilter 생성자 추가 
-  LOGIN_PREFIX 설정
-  AuthenticationManager 설정
-  AuthenticationSuccessHandler, FailHandler 설정
=> Security 설정 수정

src/main/java/stg/onyou/config/SecurityConfig.java, src/main/java/stg/onyou/config/auth/KakaoResponse.java, src/main/java/stg/onyou/config/auth/LoadUserService.java, src/main/java/stg/onyou/config/auth/PrincipalDetails.java, src/main/java/stg/onyou/config/jwt/AccessTokenAuthenticationProvider.java, src/main/java/stg/onyou/config/jwt/JwtAuthenticationFilter.java, src/main/java/stg/onyou/config/jwt/JwtAuthorizationFilter.java, src/main/java/stg/onyou/controller/UserController.java, src/main/java/stg/onyou/model/entity/Feed.java, src/main/java/stg/onyou/model/entity/Likes.java, src/main/java/stg/onyou/model/entity/User.java, src/main/java/stg/onyou/model/network/request/UserApiRequest.java, src/main/java/stg/onyou/model/network/response/UserApiResponse.java, src/main/java/stg/onyou/repository/UserRepository.java, src/main/java/stg/onyou/service/ClubApiService.java, src/main/java/stg/onyou/service/UserApiService.java
- JwtAuthenticationFilter에 path 설정
- DB에 존재하지 않는 사용자일 경우 수행하는 save 수정 
- KakaoReponse 객체 추가, PrincipalDetails 멤버 변수 수정
- User entity 스키마 수정
: birthdate -> birthday, nickname 삭제, organization_id not null -> nullable
=> jwt 수정 - 로컬에서 accessToken으로 jwt받아오는 것 성공

src/main/java/stg/onyou/service/ClubService.java
=> ErrorCode 수정

src/main/java/stg/onyou/service/ClubService.java
=> 카테고리 중복 exception 수정

src/main/resources/application.properties
=> application.properties 수정

src/main/java/stg/onyou/config/jwt/JwtAuthenticationFilter.java, src/main/java/stg/onyou/config/jwt/JwtAuthorizationFilter.java, src/main/java/stg/onyou/controller/AwsS3Controller.java, src/main/java/stg/onyou/controller/ClubController.java, src/main/java/stg/onyou/controller/FeedController.java, src/main/java/stg/onyou/exception/ErrorCode.java, src/main/java/stg/onyou/model/entity/Club.java, src/main/java/stg/onyou/model/entity/ClubSchedule.java, src/main/java/stg/onyou/model/entity/UserClub.java, src/main/java/stg/onyou/model/entity/UserClubSchedule.java, src/main/java/stg/onyou/model/network/request/ClubCreateRequest.java, src/main/java/stg/onyou/model/network/response/ClubResponse.java, src/main/java/stg/onyou/model/network/response/UserResponse.java, src/main/java/stg/onyou/service/AwsS3Service.java, src/main/java/stg/onyou/service/ClubService.java, src/main/resources/application.properties
- selectClub API에서 member에 applyStatus 값 추가
- 가입승인 로직에 NULL OR APPLIED인지 체크
- approveDate 컬럼 추가
- isClubFull 로직 수정
- ErrorCode 명칭변경
=> 220521: selectClub API 수정, S3 파일  업/다운로드 수정 

build.gradle, src/main/java/stg/onyou/config/JasyptConfig.java, src/main/resources/application.properties, src/test/java/stg/onyou/JasyptConfigTest.java
=> application.properties 암호화

.gitignore, Dockerfile, src/main/java/stg/onyou/config/AwsS3Config.java, src/main/java/stg/onyou/config/JasyptConfig.java, src/main/java/stg/onyou/controller/FileDownloadController.java, src/main/resources/application.properties, src/test/java/stg/onyou/JasyptConfigTest.java
=> 220521_jasypt

src/main/resources/application.properties
=> key값변경, db암호화 적용

src/main/java/stg/onyou/controller/ClubController.java, src/main/java/stg/onyou/controller/UserController.java, src/main/java/stg/onyou/model/entity/UserClub.java, src/main/java/stg/onyou/model/network/request/ClubRoleAllocateRequest.java, src/main/java/stg/onyou/model/network/request/ClubUpdateRequest.java, src/main/java/stg/onyou/model/network/response/UserClubResponse.java, src/main/java/stg/onyou/service/AwsS3Service.java, src/main/java/stg/onyou/service/ClubService.java, src/main/java/stg/onyou/service/UserService.java, src/main/resources/application.properties
- updateClub 추가
- allocateUserClubRole API 추가
=> updateClub, allocateUserClubRole API 추가

src/main/java/stg/onyou/controller/ClubController.java, src/main/java/stg/onyou/controller/ContentController.java, src/main/java/stg/onyou/model/Role.java, src/main/java/stg/onyou/model/entity/Content.java, src/main/java/stg/onyou/repository/ClubRepository.java, src/main/java/stg/onyou/repository/ContentRepository.java, src/main/java/stg/onyou/service/ClubService.java, src/main/java/stg/onyou/service/ContentService.java, src/main/java/stg/onyou/service/CursorResult.java
- Club cursor based pagination 구현
- Role enum 권한정의
=> 220602_pagination 구현

src/main/java/stg/onyou/controller/ClubController.java, src/main/java/stg/onyou/controller/FeedController.java, src/main/java/stg/onyou/repository/ClubRepository.java, src/main/java/stg/onyou/service/ClubService.java
Club pagination select에 Category Filtering 추가
- pagination size는 백엔드에서 상수값으로 설정 ( param에서 제외 ) 
- category 는 1개 또는 2개 선택해서 필터링 가능 ( 2개 선택 시 and 조건 ) 
- category 필터링 시에도 pagination 가능하도록 구현
=> Club Pagination에 Category Filtering 추가

src/main/java/stg/onyou/controller/FeedController.java, src/main/java/stg/onyou/model/entity/Likes.java, src/main/java/stg/onyou/repository/FeedRepository.java, src/main/java/stg/onyou/repository/LikesRepository.java, src/main/java/stg/onyou/service/AwsS3Service.java, src/main/java/stg/onyou/service/FeedService.java, src/main/java/stg/onyou/service/LikesService.java
1. like api 추가
1) '좋아요' 추가
2) '좋아요' 취소 및 다시 '좋아요'
3) feed '좋아요' 수 count
2. feed repo 부분  jpa -> spring data jpa 로 수정
3. resolve merge conflict
=> like api 추가, feed: jpa -> data jpa

src/main/java/stg/onyou/controller/CommentController.java, src/main/java/stg/onyou/controller/FeedController.java, src/main/java/stg/onyou/exception/ErrorCode.java, src/main/java/stg/onyou/model/Reason.java, src/main/java/stg/onyou/model/entity/Feed.java, src/main/java/stg/onyou/model/entity/FeedHashtag.java, src/main/java/stg/onyou/model/entity/Hashtag.java, src/main/java/stg/onyou/model/entity/Report.java, src/main/java/stg/onyou/model/entity/User.java, src/main/java/stg/onyou/model/network/response/FeedResponse.java, src/main/java/stg/onyou/repository/FeedHashtagRepository.java, src/main/java/stg/onyou/repository/HashtagRepository.java, src/main/java/stg/onyou/repository/ReportRepository.java, src/main/java/stg/onyou/service/FeedService.java, src/main/java/stg/onyou/service/HashtagService.java, src/main/java/stg/onyou/service/ReportService.java
1.Comment 는 따로 조회
2.신고(report) 기능
3.Feed 생성 시 Hashtag 추가
=> Feed (comment, report, hashtag) 기능 추가 및 수정

src/main/java/stg/onyou/controller/ClubController.java, src/main/java/stg/onyou/service/ClubService.java
createClub response 변경
- clubResponse 값 반환
=> createClub response 변경

src/main/java/stg/onyou/service/ClubService.java
=> announcement column 삭제

src/main/java/stg/onyou/controller/FeedController.java, src/main/java/stg/onyou/model/entity/FeedHashtag.java, src/main/java/stg/onyou/model/network/response/FeedResponse.java, src/main/java/stg/onyou/repository/LikesRepository.java, src/main/java/stg/onyou/service/AwsS3Service.java, src/main/java/stg/onyou/service/HashtagService.java, src/main/java/stg/onyou/service/LikesService.java
s3 file name 수정
feed response 수정 - imageUrl, hashtag, commentCount, likeYn 추가
=> feed response 수정

src/main/java/stg/onyou/controller/ClubController.java, src/main/java/stg/onyou/service/ClubService.java
- deleteSchedule API 추가
- schedule API 주소 변경
=> deleteSchedule API 추가, schedule API 주소 변경

src/main/java/stg/onyou/model/network/response/UserResponse.java, src/main/java/stg/onyou/repository/ClubQRepositoryImpl.java
=> Conflict 해결

src/main/java/stg/onyou/controller/ClubController.java, src/main/java/stg/onyou/service/ClubService.java
=> API 테스트 주소 변경

src/main/java/stg/onyou/controller/ClubController.java, src/main/java/stg/onyou/model/network/response/ClubConditionResponse.java, src/main/java/stg/onyou/model/network/response/ClubPageResponse.java, src/main/java/stg/onyou/repository/ClubQRepository.java, src/main/java/stg/onyou/service/ClubService.java
- hasNext 추가
- default size 변경 2-> 8 
- short, long desc 순서 조정
=> 220804 club page

src/main/java/stg/onyou/model/entity/User.java, src/main/java/stg/onyou/service/UserService.java
Reverts see-the-glory/on-you-backend#72
=> Revert "userResponse setThumbnail"

src/main/java/stg/onyou/controller/ClubController.java, src/main/java/stg/onyou/model/entity/Club.java, src/main/java/stg/onyou/model/entity/Feed.java, src/main/java/stg/onyou/model/entity/FeedLikes.java, src/main/java/stg/onyou/model/entity/User.java, src/main/java/stg/onyou/model/network/response/ClubConditionResponse.java, src/main/java/stg/onyou/repository/ClubQRepository.java, src/main/java/stg/onyou/repository/ClubQRepositoryImpl.java, src/main/java/stg/onyou/repository/LikesRepository.java, src/main/java/stg/onyou/service/ClubService.java, src/main/java/stg/onyou/service/LikesService.java, src/main/resources/application.properties
- feedNum, clubLikesNum 커스텀 페이지네이션 추가 
- showRecruitingOnly, showMemberBetween 조건 추가
=> Custom Pagination 완성

src/main/java/stg/onyou/controller/ClubController.java, src/main/java/stg/onyou/controller/FeedController.java, src/main/java/stg/onyou/model/entity/Club.java, src/main/java/stg/onyou/model/network/request/ClubUpdateRequest.java, src/main/java/stg/onyou/model/network/response/ClubConditionResponse.java, src/main/java/stg/onyou/model/network/response/ClubResponse.java, src/main/java/stg/onyou/model/network/response/FeedResponse.java, src/main/java/stg/onyou/repository/ClubQRepositoryImpl.java, src/main/java/stg/onyou/service/ClubService.java, src/main/java/stg/onyou/service/UserService.java
- myClub API 추가
- club - contactPhone 추가
- feedResponse DTO : feedId -> id 로 변경
=> myClub API 추가, club.contactPhone 추가

src/main/java/stg/onyou/repository/ClubQRepositoryImpl.java
[Fix] Club Category 필터 default 0 일 때 처리
=> [Fix] Club Category 필터 default 0 일 때 처리

src/main/java/stg/onyou/repository/ClubQRepositoryImpl.java
=> [Fix] Category

src/main/java/stg/onyou/model/network/request/ClubUpdateRequest.java, src/main/java/stg/onyou/service/ClubService.java
[Add] updateClub API : Category UPDATE
=> [Add] updateClub API : Category UPDATE

src/main/java/stg/onyou/config/jwt/AccessTokenAuthenticationProvider.java, src/main/java/stg/onyou/controller/UserController.java, src/main/java/stg/onyou/model/entity/User.java, src/main/java/stg/onyou/model/network/request/UserFindIdRequest.java, src/main/java/stg/onyou/model/network/response/UserUpdateRequest.java, src/main/java/stg/onyou/repository/ClubQRepositoryImpl.java, src/main/java/stg/onyou/repository/UserRepository.java, src/main/java/stg/onyou/service/ClubService.java, src/main/java/stg/onyou/service/UserService.java
1.account_email -> email로 수정
2.findUserId Api
=> findUserId 

src/main/java/stg/onyou/repository/ClubScheduleRepository.java, src/main/java/stg/onyou/service/ClubService.java
[Fix] ClubSchedulAPI 정렬 stardate기준으로 변경
=> [Fix] ClubSchedulAPI 정렬 stardate기준으로 변경

src/main/java/stg/onyou/controller/FeedController.java, src/main/java/stg/onyou/repository/FeedQRepository.java, src/main/java/stg/onyou/repository/FeedQRepositoryImpl.java, src/main/java/stg/onyou/service/FeedService.java
[Add] selectFeedListByClub API
=> [Add] selectFeedListByClub API

src/main/java/stg/onyou/controller/CommentController.java, src/main/java/stg/onyou/model/network/response/ClubConditionResponse.java, src/main/java/stg/onyou/model/network/response/ClubMessagesResponse.java, src/main/java/stg/onyou/model/network/response/ClubNotificationResponse.java, src/main/java/stg/onyou/model/network/response/ClubResponse.java, src/main/java/stg/onyou/model/network/response/ClubScheduleResponse.java, src/main/java/stg/onyou/model/network/response/CommentResponse.java, src/main/java/stg/onyou/model/network/response/FeedResponse.java, src/main/java/stg/onyou/model/network/response/MyClubResponse.java, src/main/java/stg/onyou/model/network/response/UserClubResponse.java, src/main/java/stg/onyou/model/network/response/UserNotificationResponse.java, src/main/java/stg/onyou/model/network/response/UserResponse.java, src/main/java/stg/onyou/service/FeedService.java
[Add] Response에 타임존 설정: Asia/Seoul
=> [Add] Response에 타임존 설정: Asia/Seoul

src/main/java/stg/onyou/model/entity/ClubSchedule.java, src/main/java/stg/onyou/service/ClubService.java
[Fix] ClubUpdate API에서 category1개더라도 2개로 update가능하도록
=> [Fix] ClubUpdate API에서 category1개더라도 2개로 update가능하도록

src/main/java/stg/onyou/service/ClubService.java
[Fix] joinOrCancel API 수정: Long 비교 연산
=> [Fix] joinOrCancel API 수정: Long 비교 연산

src/main/java/stg/onyou/repository/ClubCategoryRepository.java, src/main/java/stg/onyou/service/ClubService.java
[Fix] clubUpdate API : category 부분 수정
=> [Fix] clubUpdate API : category 부분 수정

src/main/java/stg/onyou/service/ClubService.java
[Fix] selectClub user thumbnail 추가
=> [Fix] selectClub user thumbnail 추가

src/main/java/stg/onyou/service/ClubService.java
[Fix] selectClubScheduleList API thumbnail
=> [Fix] selectClubScheduleList API thumbnail 

src/main/java/stg/onyou/controller/CommentController.java, src/main/java/stg/onyou/model/network/response/CommentResponse.java, src/main/java/stg/onyou/model/network/response/FeedResponse.java, src/main/java/stg/onyou/repository/FeedQRepositoryImpl.java, src/main/java/stg/onyou/service/FeedService.java
[Fix] Thumbnail 추가 : feed, comment
=> [Fix] Thumbnail 추가 : feed, comment

src/main/java/stg/onyou/service/AwsS3Service.java, src/main/resources/application-dev.properties, src/main/resources/application-prod.properties
1. feed image 크기 압축 부분 원복
2. 서버 시간 Asia/Seoul 설정
=> bug fix, 서버시간 변경

src/main/java/stg/onyou/model/network/request/ClubScheduleCreateRequest.java
=> Timezone 수정

src/main/java/stg/onyou/controller/ClubController.java, src/main/java/stg/onyou/controller/FeedController.java, src/main/java/stg/onyou/exception/ErrorCode.java, src/main/java/stg/onyou/model/Role.java, src/main/java/stg/onyou/service/ClubService.java, src/main/java/stg/onyou/service/FeedService.java
deleteFeed, deleteClub, withdrawClub 수정 및 추가
=> deleteFeed, deleteClub, withdrawClub 수정 및 추가

build.gradle, src/main/java/stg/onyou/controller/TestController.java, src/main/java/stg/onyou/controller/TestDTO.java, src/main/java/stg/onyou/model/network/FcmMessage.java, src/main/java/stg/onyou/service/FirebaseCloudMessageService.java, src/main/resources/application.properties, src/main/resources/firebase/firebase_service_key.json
[Add] FirebaseCloudMessaging 구현 및 test api 구현
=> [Add] FirebaseCloudMessaging 구현 및 test api 구현

src/main/java/stg/onyou/repository/FeedQRepositoryImpl.java, src/main/java/stg/onyou/service/FeedService.java
=> [Fix] Comment 카운팅 문제

src/main/java/stg/onyou/model/network/response/ClubResponse.java, src/main/java/stg/onyou/service/ClubService.java
[Fix] 삭제된 club의 creatorName 가져오는 것으로 인한 NPE
=> [Fix] 삭제된 club의 creatorName 가져오는 것으로 인한 NPE

src/main/java/stg/onyou/controller/CommentController.java, src/main/java/stg/onyou/controller/FeedController.java, src/main/java/stg/onyou/model/entity/Comment.java, src/main/java/stg/onyou/model/entity/CommentLikes.java, src/main/java/stg/onyou/model/enums/PreferType.java, src/main/java/stg/onyou/model/network/request/CommentCreateRequest.java, src/main/java/stg/onyou/model/network/response/CommentResponse.java, src/main/java/stg/onyou/repository/CommentLikesRepository.java, src/main/java/stg/onyou/repository/CommentRepository.java, src/main/java/stg/onyou/repository/FeedLikesRepository.java, src/main/java/stg/onyou/service/CommentService.java, src/main/java/stg/onyou/service/FeedService.java, src/main/java/stg/onyou/service/LikesService.java, src/main/resources/application-dev.yml
댓글 좋아요 , UserPrefernece type 추가
=> 댓글 좋아요 , UserPrefernece type 추가 
